fix msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -33,16 +33,21 @@ jobs:
       working-directory: ${{github.workspace}}
       run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
 
-    - name: Upload artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: CFGComp
-        path: ${{github.workspace}}/x64/${{env.BUILD_CONFIGURATION}}/CFGComp.exe
+    - name: Check for executable
+      run: |
+        if (Test-Path "${{github.workspace}}\x64\${{env.BUILD_CONFIGURATION}}\CFGComp.exe") {
+          echo "Executable found"
+        } else {
+          echo "Executable not found"
+          exit 1
+        }
 
     - name: Create Release
       if: startsWith(github.ref, 'refs/tags/')
       uses: softprops/action-gh-release@v1
       with:
-        files: ${{github.workspace}}/x64/${{env.BUILD_CONFIGURATION}}/CFGComp.exe
+        files: ${{github.workspace}}\x64\${{env.BUILD_CONFIGURATION}}\CFGComp.exe
+        draft: false
+        prerelease: false
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
